name: App
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.10
  image_picker: ^0.8.7+4
  http: ^0.13.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/plant.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images.jpeg
    - assets/index.html
